name: Vercel Preview Deploy
env:
  VERCEL_ORG_ID: $
  VERCEL_PROJECT_ID: $

on:
  pull_request:
    branches:
      - "develop"

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=$

      - name: Build Project Artifacts
        run: vercel build --token=$

      - name: Assign beta domain
        run: |
          vercel deploy --prebuilt --token=$ > domain.txt
          vercel alias set `cat domain.txt` phototicon-stag.vercel.app --scope $ --token $
