name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    
on:
  pull_request:
    branches:
      - "main"
    types:
      - "closed"


jobs:
  Prod-Deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "junbeomAn"
          git config user.email "wnsqja8744@github.com"

      - name: Create deployment branch
        run: |
          DATE=$(date +'%Y%m%d-%H%M%S')
          DEPLOY_BRANCH="deploy-${DATE}"
          git checkout -b $DEPLOY_BRANCH
          git push origin $DEPLOY_BRANCH
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts
        run: |
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
          
    